### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [9]:
vector = np.random.rand(10)

In [10]:
vector

array([0.44594225, 0.57625719, 0.3068445 , 0.28141097, 0.0992275 ,
       0.05510841, 0.67526682, 0.96333843, 0.9248477 , 0.12520891])

In [11]:
vector.shape

(10,)

In [16]:
matrix = np.array([[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]])

In [17]:
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [18]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [26]:
new_vector = np.round(vector + 10, 2)

In [27]:
new_vector

array([10.45, 10.58, 10.31, 10.28, 10.1 , 10.06, 10.68, 10.96, 10.92,
       10.13])

In [28]:
new_matrix = matrix * 2

In [29]:
new_matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [30]:
square_vector = np.square(vector)

In [31]:
square_vector

array([0.19886449, 0.33207235, 0.09415355, 0.07919213, 0.0098461 ,
       0.00303694, 0.45598528, 0.92802093, 0.85534328, 0.01567727])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [33]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [62]:
result_matrix = np.dot(B, A)

In [63]:
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [64]:
matrix_mult_vector = np.dot(result_matrix, C)

In [65]:
display(matrix_mult_vector)

array([[0.5202],
       [0.2846]])

In [66]:
matrix_mult_matrix = np.dot(result_matrix, D)

In [67]:
display(matrix_mult_matrix)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [68]:
display(result_matrix.T)

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [69]:
vector

array([0.44594225, 0.57625719, 0.3068445 , 0.28141097, 0.0992275 ,
       0.05510841, 0.67526682, 0.96333843, 0.9248477 , 0.12520891])

In [70]:
display(vector.T)

array([0.44594225, 0.57625719, 0.3068445 , 0.28141097, 0.0992275 ,
       0.05510841, 0.67526682, 0.96333843, 0.9248477 , 0.12520891])

**Спостереження**
Не бачу зміни структури при транспонуванні вектора, хоча я думала, що вектор-строка має стати вектор-стовпцем

In [71]:
column_vector = np.expand_dims(vector, axis=1)

In [72]:
display(column_vector)

array([[0.44594225],
       [0.57625719],
       [0.3068445 ],
       [0.28141097],
       [0.0992275 ],
       [0.05510841],
       [0.67526682],
       [0.96333843],
       [0.9248477 ],
       [0.12520891]])

**Спостереження**
Тепер структура змінилася і вектор став вектор-стовпцем

In [73]:
transpose_column_vector = column_vector.T
display(transpose_column_vector)
transpose_column_vector.shape

array([[0.44594225, 0.57625719, 0.3068445 , 0.28141097, 0.0992275 ,
        0.05510841, 0.67526682, 0.96333843, 0.9248477 , 0.12520891]])

(1, 10)

In [74]:
column_vector.shape

(10, 1)